language: r
sudo: required
dist: trusty

addons:
  apt:
    packages:
    - libproj-dev
    - libgdal-dev

r_github_packages:
  - jimhester/lintr
  - jimhester/covr
  - hadley/pkgdown

after_success:
  - Rscript -e 'covr::codecov()'
  - Rscript -e 'pkgdown::build_site()'

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_PAT
  keep-history: true
  local-dir: docs
  on:
    branch: master
