language: r
cache: packages
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install r-cran-rgdal
  - cd rdefra

r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e 'covr::codecov()'
